# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger:
#- main

#pool:
  #vmImage: ubuntu-latest

#steps:
#- script: echo Hello, world!
  #displayName: 'Run a one-line script'

#- script: |
    #echo Add other tasks to build, test, and deploy your project.
    #echo See https://aka.ms/yaml
  #displayName: 'Run a multi-line script'

# azure-pipelines.yml

trigger:
  branches:
    include:
      - main  # Replace with your branch name if needed

pool:
  vmImage: 'ubuntu-latest'

variables:
  PLAYWRIGHT_SERVICE_URL: '$(PLAYWRIGHT_SERVICE_URL)'  # Set a default value or reference a pipeline variable

steps:
  - task: UseNode@1
    inputs:
      versionSpec: '14.x'  # Replace with your required Node.js version
    displayName: 'Install Node.js'

  - script: |
      echo "Installing dependencies"
      npm install
    displayName: 'Install dependencies'

  - script: |
      echo "Running tests with Playwright using service URL: $(PLAYWRIGHT_SERVICE_URL)"
      # Use the environment variable in your Playwright command or script
      PLAYWRIGHT_SERVICE_URL=$(PLAYWRIGHT_SERVICE_URL) npm test
    displayName: 'Run Playwright tests'
    env:
      PLAYWRIGHT_SERVICE_URL: $(PLAYWRIGHT_SERVICE_URL)  # Inject the variable into the environment
